dist: xenial
language: node_js
node_js:
  - 8
services: docker

addons:
  apt:
    packages:
    - qemu-user-static
    - pxz

cache:
  - npm
  - directories:
      - build/appimage-build-ia32
      - build/appimage-build-x64
      - build/appimage-build-arm
      - build/appimage-build-arm64

_prep_env: &_prep_env
  stage: "Prepare Env"
  os: linux
  env: TGT_ARCH=x64
  if: tag IS present
  script: "./build/step1-prepare-env.bash"

_build_appimagetool: &_build_appimagetool
  stage: "Build appimagetool"
  os: linux
  env: TGT_ARCH=x64
  if: tag IS present
  script: "./build/step2-build-appimagetool.bash"

_build_sodium: &_build_sodium
  stage: "Build sodium"
  os: linux
  env: TGT_ARCH=x64
  if: tag IS present
  script: "./build/step3-build-sodium-native.bash"

_build_appimage: &_build_appimage
  stage: "Build appimage"
  os: linux
  env: TGT_ARCH=x64
  if: tag IS present
  script: "./build/step4-build-n3h-appimage.bash"

stages:
  - "Test"
  - "Prepare env"
  - "Build appimagetool"
  - "Build sodium"
  - "Build appimage"
  - "Build electron"

jobs:
  include:
    - name: "Windows test"
      stage: "Test"
      os: windows
      script:
        - npm test
    - name: "Linux test"
      stage: "Test"
      os: linux
      script:
        - npm test
    - name: "Mac test"
      stage: "Test"
      os: osx
      script:
        - npm test

    - name: "Windows build"
      stage: "Build electron"
      if: tag IS present
      os: linux
      script:
        - |
          docker run --rm \
            $(env | \
              grep -Eo '^[^\s=]*(DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_)[^\s=]*' | \
              sed '/^$/d;s/^/-e /' | \
              paste -sd ' ' \
            ) \
            -v ${PWD}:/project \
            -v ~/.cache/electron:/root/.cache/electron \
            -v ~/.cache/electron-builder:/root/.cache/electron-builder \
            electronuserland/builder:wine \
            /bin/bash -c "./build/release-build-electron.bash --win --x64"

    - name: "Mac build"
      stage: "Build electron"
      os: osx
      if: tag IS present
      script:
        - ./build/release-build-electron.bash --mac --x64

    - name: "Prepare env ia32"
      <<: *_prep_env
      env: TGT_ARCH=ia32
    - name: "Build appimagetool ia32"
      <<: *_build_appimagetool
      env: TGT_ARCH=ia32
    - name: "Build sodium ia32"
      <<: *_build_sodium
      env: TGT_ARCH=ia32
    - name: "Build appimage ia32"
      <<: *_build_appimage
      env: TGT_ARCH=ia32

    - name: "Prepare env x64"
      <<: *_prep_env
      env: TGT_ARCH=x64
    - name: "Build appimagetool x64"
      <<: *_build_appimagetool
      env: TGT_ARCH=x64
    - name: "Build sodium x64"
      <<: *_build_sodium
      env: TGT_ARCH=x64
    - name: "Build appimage x64"
      <<: *_build_appimage
      env: TGT_ARCH=x64

    - name: "Prepare env arm"
      <<: *_prep_env
      env: TGT_ARCH=arm
    - name: "Build appimagetool arm"
      <<: *_build_appimagetool
      env: TGT_ARCH=arm
    - name: "Build sodium arm"
      <<: *_build_sodium
      env: TGT_ARCH=arm
    - name: "Build appimage arm"
      <<: *_build_appimage
      env: TGT_ARCH=arm

    - name: "Prepare env arm64"
      <<: *_prep_env
      env: TGT_ARCH=arm64
    - name: "Build appimagetool arm64"
      <<: *_build_appimagetool
      env: TGT_ARCH=arm64
    - name: "Build sodium arm64"
      <<: *_build_sodium
      env: TGT_ARCH=arm64
    - name: "Build appimage arm64"
      <<: *_build_appimage
      env: TGT_ARCH=arm64

deploy:
  provider: releases
  api_key:
    secure: xZGYRJ5E4BnUgRBDIkqeNqDSyUdvZAOJHqey73ZpHfs834kKhJ3x5MMmHdvP0bXA+OVUu+fnIfuuNH158hc7Mo0BPkJN4nkOcl0wjNUpqfg2ujAfcbAehtkz1cpv8AZRNSrL1xrtchOEY7jnuGyv+O05uROxTxvtT3TsGql1Qc62M+MglZtz2bALMbFrTMfxqcXH32h431OIXKZORkQUXgsFvbXg0J2ghzDLMknTlDZF2W2/Xds77FTPe9B7gNiNRvL9y5bU/Y03k1efIcfdMNSL8upGhpPhgDiipPjGFUmyarfcXvd6v2HQNrPTAHXoXHReIqAapNUqU5bWMQ9Kd+f5BAfybKIce6q+m4JvcoritCUJBP9uV9+7oA8rek0Cvykfc1MGFWHSy5Wv1iheUh9T3i/hlrqSZqad0LYw7tHQg1JLbFQOaqlIBmy8fYFsV3k9L1222u9EdWzHTO5kpHOHXeXRaeKrHCMycVWcVINXfKXrMIWO4sxAY71IRBTLQJUFPUUTjcSgkWB0yHZFyli8qEJmVvZikcylz89eVY2iTJepddKnsnSWPOQP1ZA1JRLP0QjhcWMfHPrrMWm2WUfBNebIkmPQylidWkvPBHca4HM7DTYuV9BbOZiR8prQ58v7zEVTxxr9ODFeFcjRcYaFpa+nQKRzSUdvsO1zUpU=
  file_glob: true
  file:
  - build/appimage-build*/output/*
  - build/electron-build/dist/n3h*
  skip_cleanup: true
  prerelease: true
  name: $TRAVIS_TAG
  on:
    tags: true
    repo: holochain/n3h
