jobs:
  include:
    - name: "windows"
      os: windows
      language: node_js
      node_js: "8"
      install:
      before_script:
        - npm install lerna
        - npm run bootstrap
    - name: "linux"
      os: linux
      language: node_js
      node_js: "8"
      install:
      before_script:
        - npm install lerna
        - npm run bootstrap
    - name: "osx"
      os: osx
      language: node_js
      node_js: "8"
      install:
      before_script:
        - npm install lerna
        - npm run bootstrap
        
